version: '3.8'

services:
  frontend:
    build:
      context: ./salonease-mvp/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./salonease-mvp/frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./salonease-mvp/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./salonease-mvp/backend:/app
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=salonease
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npx sequelize-cli db:migrate && npm start"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salonease
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
