services:
  frontend:
    build:
      context: ./salonease-mvp/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./salonease-mvp/frontend:/app:delegated
      - /app/node_modules
    environment:
      - REACT_APP_MAILERLITE_API_KEY=${REACT_APP_MAILERLITE_API_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./salonease-mvp/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./salonease-mvp/backend:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=salonease
      - DB_HOST=db
      - JWT_SECRET=the key is used mostly for testing
      - DB_POOL_MAX=5
      - DB_POOL_MIN=0
      - DB_POOL_IDLE=10000
      - DB_POOL_ACQUIRE=30000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npx sequelize-cli db:migrate && nodemon src/server.js"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salonease
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.net
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./salonease-mvp/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
