export const AVAILABILITY_TYPES = {
  AVAILABILITY: 'AVAILABILITY',
  TIME_OFF: 'TIME_OFF'
};

export const BOOKING_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
  RESCHEDULED: 'RESCHEDULED'
};
